version: '3'
services:
  db:
    image: postgres:9.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    #when upgrading elasticsearch server on local machine:
    #network_mode: "host"
    ports:
      - "5432:5432"
  elastic:
    image: elasticsearch:6.7.2
    # we commented out the next 2 lines so version 6 could work.
    # TODO: find out if it's needed / how to make it work
    # volumes:
    #   - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SEARCHBOX_URL=elastic
    volumes:
      - .:/speakerinnen_liste
      - bundle:/bundle
    #when upgrading elasticsearch server on local machine:
    #network_mode: "host"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elastic
    tty: true
    stdin_open: true
volumes:
  bundle:
  postgres_data:
  # elastic_data:
