name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    #Gitrunner hosted by Github
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make setup

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: build
    - name: Run all tests
      run: make test


